# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2e6c3aace3f6919517e0f945339af9e63faebe48e0e5eaa3bdb550bbfd8a0338f1e636d6cdc1669aee5876db732a26bd52899fdfa5255a4c5b256cc4b649311a

test:
  secret_key_base: 408e21c03625997317ac70d56abef2ccd79eae67fd57bf242c33fb7613fb5ca27308096141c6877e956079b4c7e8a10df19063379536c4f537c0ca054baa1731

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
