
puts 'Residential --> 0'
residential = Kind.create(name: 'residential')
commercial = Kind.create(name: 'commercial')
office = Kind.create(name: 'office')
# health = Kind.create(name: 'health')
education = Kind.create(name: 'education')
cultural = Kind.create(name: 'cultural')
publics = Kind.create(name: 'publics')


residential.buildings << Building.create(name: 'ahuehuetes 2105',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '435.00 sqm' ,
                thumbnail: 'thumbnail/ahuehuetes.jpg',
                images: ['buildings/ahuehuetes-2105/ahuehuetes1.jpg',
                         'buildings/ahuehuetes-2105/ahuehuetes2.jpg',
                         'buildings/ahuehuetes-2105/ahuehuetes3.jpg',
                         'buildings/ahuehuetes-2105/ahuehuetes4.jpg',
                         'buildings/ahuehuetes-2105/ahuehuetes5.jpg',
                         'buildings/ahuehuetes-2105/ahuehuetes6.jpg'],
                imagesori: ['buildingsorigin/Residential/AHUEHUETES/AHUEHUETES1.jpg',
                            'buildingsorigin/Residential/AHUEHUETES/AHUEHUETES2.jpg',
                            'buildingsorigin/Residential/AHUEHUETES/AHUEHUETES3.jpg',
                            'buildingsorigin/Residential/AHUEHUETES/AHUEHUETES4.jpg',
                            'buildingsorigin/Residential/AHUEHUETES/AHUEHUETES5.jpg',
                            'buildingsorigin/Residential/AHUEHUETES/AHUEHUETES6.jpg'])


residential.buildings << Building.create(name: 'Sauces 902',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '315.00 sqm' ,
                thumbnail: 'buildings/sauces/SAUSE.jpg',
                images: ['buildings/sauces/SAUSES1.jpg',
                         'buildings/sauces/SAUSES2.jpg',
                         'buildings/sauces/SAUSES3.jpg',
                         'buildings/sauces/SAUSES4.jpg'],
                imagesori: ['buildingsorigin/Residential/SAUSES902/SAUSES1.jpg',
                            'buildingsorigin/Residential/SAUSES902/SAUSES2.jpg',
                            'buildingsorigin/Residential/SAUSES902/SAUSES3.jpg',
                            'buildingsorigin/Residential/SAUSES902/SAUSES4.jpg'])


residential.buildings << Building.create(name: 'Carso AP',
                description: '',
                year: '2017',
                location: 'Mexico City',
                area: '350.00 sqm' ,
                thumbnail: 'buildings/carso/carsom.jpg',
                images: ['buildings/carso/CARSOAP1.jpg',
                         'buildings/carso/CARSOAP2.jpg',
                         'buildings/carso/CARSOAP3.jpg',
                         #'buildings/carso/CARSOAP4.jpg',
                         'buildings/carso/CARSOAP5.jpg',
                         'buildings/carso/CARSOAP6.jpg',
                         'buildings/carso/CARSOAP7.jpg',
                         'buildings/carso/CARSOAP8.jpg',
                         'buildings/carso/CARSOAP9.jpg',
                         'buildings/carso/CARSOAP10.jpg',
                         'buildings/carso/CARSOAP11.jpg',
                         'buildings/carso/CARSOAP12.jpg',
                         'buildings/carso/CARSOAP13.jpg',
                         'buildings/carso/CARSOAP14.jpg',
                         'buildings/carso/CARSOAP15.jpg'],
                imagesori: ['buildingsorigin/Residential/CARSOAP/CARSOAP1.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP2.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP3.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP4.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP5.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP6.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP7.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP8.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP9.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP10.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP11.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP12.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP13.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP14.jpg',
                            'buildingsorigin/Residential/CARSOAP/CARSOAP15.jpg'])

residential.buildings << Building.create(name: 'bosque de canelos',
                description: '',
                year: '2015',
                location: 'Mexico City',
                area: '320 sqm' ,
                thumbnail: 'thumbnail/residential/bosquedecanelos.jpg',
                images: ['buildings/bosque-de-canelos/CANELOS1.jpg',
                         'buildings/bosque-de-canelos/CANELOS2.jpg',
                         'buildings/bosque-de-canelos/CANELOS3.jpg',
                         'buildings/bosque-de-canelos/CANELOS4.jpg',
                         'buildings/bosque-de-canelos/CANELOS5.jpg',
                         'buildings/bosque-de-canelos/CANELOS6.jpg',
                         'buildings/bosque-de-canelos/CANELOS7.jpg',
                         'buildings/bosque-de-canelos/CANELOS8.jpg',
                         'buildings/bosque-de-canelos/CANELOS9.jpg',
                         'buildings/bosque-de-canelos/CANELOS10.jpg',
                         'buildings/bosque-de-canelos/CANELOS11.jpg',
                         'buildings/bosque-de-canelos/CANELOS12.jpg'],
                imagesori: ['buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS1.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS2.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS3.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS4.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS5.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS6.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS7.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS8.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS9.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS10.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS11.jpg',
                            'buildingsorigin/Residential/BOSQUEDECANELOS/CANELOS12.jpg'])


residential.buildings << Building.create(name: 'departamento ppg',
                description: '',
                year: '2018',
                location: 'Mexico City',
                area: '430 sqm' ,
                thumbnail: 'thumbnail/ppg.jpg',
                images: ['buildings/departamento-ppg/departamentoppg1.jpg',
                         'buildings/departamento-ppg/departamentoppg2.jpg',
                         'buildings/departamento-ppg/departamentoppg3.jpg',
                         'buildings/departamento-ppg/departamentoppg4.jpg',
                         'buildings/departamento-ppg/departamentoppg5.jpg'],
                imagesori: ['buildingsorigin/Residential/DEPARTAMENTOPPG/PPG1.jpg',
                            'buildingsorigin/Residential/DEPARTAMENTOPPG/PPG2.jpg',
                            'buildingsorigin/Residential/DEPARTAMENTOPPG/PPG3.jpg',
                            'buildingsorigin/Residential/DEPARTAMENTOPPG/PPG4.jpg',
                            'buildingsorigin/Residential/DEPARTAMENTOPPG/PPG5.jpg'])

residential.buildings << Building.create(name: 'San Nicolás VV',
                description: '',
                year: '2019',
                location: 'Valle de Bravo',
                area: '22,000 sqm' ,
                thumbnail: 'https://res.cloudinary.com/ablanco/image/upload/v1576101585/nicolas.jpg',
                images: ['https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas1.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas2.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas3.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas4.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas5.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas6.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas7.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas8.jpg'],
                imagesori: ['https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas1.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas2.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas3.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas4.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas5.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas6.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas7.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102456/san-nicolas/sannicolas8.jpg'])


residential.buildings << Building.create(name: 'tamarindos 902',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '370.00 sqm' ,
                thumbnail: 'thumbnail/residential/tamarindos.jpg',
                images: ['buildings/tamarindos-902/TAMARINDOS-902-1.jpg',
                         'buildings/tamarindos-902/TAMARINDOS-902-2.jpg',
                         'buildings/tamarindos-902/TAMARINDOS-902-3.jpg',
                         'buildings/tamarindos-902/TAMARINDOS-902-4.jpg',
                         'buildings/tamarindos-902/TAMARINDOS-902-5.jpg'],
                imagesori: ['buildingsorigin/Residential/TAMARINDOS902/TAMARINDOS1.jpg',
                            'buildingsorigin/Residential/TAMARINDOS902/TAMARINDOS2.jpg',
                            'buildingsorigin/Residential/TAMARINDOS902/TAMARINDOS3.jpg',
                            'buildingsorigin/Residential/TAMARINDOS902/TAMARINDOS4.jpg',
                            'buildingsorigin/Residential/TAMARINDOS902/TAMARINDOS5.jpg'])



residential.buildings << Building.create(name: 'u house',
                description: '',
                year: '2017',
                location: 'Valle de Bravo',
                area: '610 sqm' ,
                thumbnail: 'thumbnail/uh-house.jpg',
                images: ['buildings/u-house-bosque-de-canelos/uhouse1.jpg',
                         'buildings/u-house-bosque-de-canelos/uhouse2.jpg',
                         'buildings/u-house-bosque-de-canelos/uhouse3.jpg',
                         'buildings/u-house-bosque-de-canelos/uhouse4.jpg',
                         'buildings/u-house-bosque-de-canelos/uhouse5.jpg',
                         'buildings/u-house-bosque-de-canelos/uhouse6.jpg'],
                imagesori: ['buildingsorigin/Residential/UHOUSE/UHOUSE1.JPG',
                            'buildingsorigin/Residential/UHOUSE/UHOUSE2.JPG',
                            'buildingsorigin/Residential/UHOUSE/UHOUSE3.JPG',
                            'buildingsorigin/Residential/UHOUSE/UHOUSE4.JPG',
                            'buildingsorigin/Residential/UHOUSE/UHOUSE5.JPG',
                            'buildingsorigin/Residential/UHOUSE/UHOUSE6.JPG'])

residential.buildings << Building.create(name: 're 32 house',
                description: '',
                year: '2012',
                location: 'Mexico City',
                area: '420 sqm' ,
                thumbnail: 'thumbnail/rehouse.jpg',
                images: ['buildings/RE32HOUSE/rehouse1.jpg',
                         'buildings/RE32HOUSE/rehouse2.jpg',
                         'buildings/RE32HOUSE/rehouse3.jpg',
                         'buildings/RE32HOUSE/rehouse4.jpg',
                         'buildings/RE32HOUSE/rehouse5.jpg',
                         'buildings/RE32HOUSE/rehouse6.jpg',
                         'buildings/RE32HOUSE/rehouse7.jpg'],
                imagesori: ['buildingsorigin/Residential/RE32HOUSE/rehouse1.jpg',
                            'buildingsorigin/Residential/RE32HOUSE/rehouse2.jpg',
                            'buildingsorigin/Residential/RE32HOUSE/rehouse3.jpg',
                            'buildingsorigin/Residential/RE32HOUSE/rehouse4.jpg',
                            'buildingsorigin/Residential/RE32HOUSE/rehouse5.jpg',
                            'buildingsorigin/Residential/RE32HOUSE/rehouse6.jpg',
                            'buildingsorigin/Residential/RE32HOUSE/rehouse7.jpg'])





# -----------------------------------------------------------------------------
puts 'Commercial --> 1'
commercial.buildings << Building.create(name: 'be concept store',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '300 sqm' ,
                thumbnail: 'thumbnail/commercial/beconceptm.jpg',
                images: ['buildings/be-concept-store/beconceptstore1.jpg',
                         'buildings/be-concept-store/beconceptstore2.jpg',
                         'buildings/be-concept-store/beconceptstore3.jpg',
                         'buildings/be-concept-store/beconceptstore4.jpg',
                         'buildings/be-concept-store/beconceptstore5.jpg',
                         'buildings/be-concept-store/beconceptstore6.jpg',
                         'buildings/be-concept-store/beconceptstore7.jpg',
                         'buildings/be-concept-store/beconceptstore8.jpg',
                         'buildings/be-concept-store/beconceptstore9.jpg'],
                imagesori: ['buildingsorigin/Commercial/BECONCEPTSTORE/beconceptstore1.jpg',
                            'buildingsorigin/Commercial/BECONCEPTSTORE/beconceptstore2.jpg',
                            'buildingsorigin/Commercial/BECONCEPTSTORE/beconceptstore3.jpg',
                            'buildingsorigin/Commercial/BECONCEPTSTORE/beconceptstore4.jpg',
                            'buildingsorigin/Commercial/BECONCEPTSTORE/beconceptstore5.jpg',
                            'buildingsorigin/Commercial/BECONCEPTSTORE/beconceptstore6.jpg',
                            'buildingsorigin/Commercial/BECONCEPTSTORE/beconceptstore7.jpg',
                            'buildingsorigin/Commercial/BECONCEPTSTORE/beconceptstore8.jpg',
                            'buildingsorigin/Commercial/BECONCEPTSTORE/beconceptstore9.jpg'])

commercial.buildings << Building.create(name: 'raw republic',
                description: '',
                year: '2017',
                location: 'Mexico City',
                area: '280 sqm' ,
                thumbnail: 'thumbnail/commercial/rawrepublicm.jpg',
                images: ['buildings/raw-republic/RAWREPUBLIC1.jpg',
                         'buildings/raw-republic/RAWREPUBLIC2.jpg',
                         'buildings/raw-republic/RAWREPUBLIC3.jpg',
                         'buildings/raw-republic/RAWREPUBLIC4.jpg',
                         'buildings/raw-republic/RAWREPUBLIC5.jpg',
                         'buildings/raw-republic/RAWREPUBLIC6.jpg',
                         'buildings/raw-republic/RAWREPUBLIC7.jpg',
                         'buildings/raw-republic/RAWREPUBLIC8.jpg',
                         'buildings/raw-republic/RAWREPUBLIC9.jpg',
                         'buildings/raw-republic/RAWREPUBLIC10.jpg',
                         'buildings/raw-republic/RAWREPUBLIC11.jpg',
                         'buildings/raw-republic/RAWREPUBLIC12.jpg',
                         'buildings/raw-republic/RAWREPUBLIC13.jpg',
                         'buildings/raw-republic/RAWREPUBLIC14.jpg'],
                imagesori: ['buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC1.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC2.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC3.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC4.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC5.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC6.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC7.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC8.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC9.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC10.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC11.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC12.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC13.jpg',
                            'buildingsorigin/Commercial/RAWREPUBLIC/RAWREPUBLIC14.jpg'])


commercial.buildings << Building.create(name: 'ten tei',
                description: '',
                year: '2018',
                location: 'Mexico City',
                area: '70 sqm',
                thumbnail: 'thumbnail/commercial/tenteim.jpg',
                images: ['buildings/ten-tei/TENTEI1.jpg',
                         'buildings/ten-tei/TENTEI2.jpg',
                         'buildings/ten-tei/TENTEI3.jpg',
                         'buildings/ten-tei/TENTEI4.jpg',
                         'buildings/ten-tei/TENTEI5.jpg',
                         'buildings/ten-tei/TENTEI6.jpg',
                         'buildings/ten-tei/TENTEI7.jpg',
                         'buildings/ten-tei/TENTEI8.jpg',
                         'buildings/ten-tei/TENTEI9.jpg',
                         'buildings/ten-tei/TENTEI10.jpg',
                         'buildings/ten-tei/TENTEI11.jpg',
                         'buildings/ten-tei/TENTEI12.jpg'],
                imagesori: ['buildingsorigin/Commercial/TENTEI/TENTEI1.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI2.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI3.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI4.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI5.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI6.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI7.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI8.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI9.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI10.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI11.jpg',
                            'buildingsorigin/Commercial/TENTEI/TENTEI12.jpg'])

commercial.buildings << Building.create(name: 'in the mix',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '110.00 sqm',
                thumbnail: 'thumbnail/inthemix.jpg',
                images: ['buildings/in-the-mix/INTHEMIX1.jpg',
                         'buildings/in-the-mix/INTHEMIX2.jpg',
                         'buildings/in-the-mix/INTHEMIX3.jpg',
                         'buildings/in-the-mix/INTHEMIX4.jpg',
                         'buildings/in-the-mix/INTHEMIX5.jpg',
                         'buildings/in-the-mix/INTHEMIX6.jpg'],
                imagesori: ['buildingsorigin/Commercial/INTHEMIX/inthemix1.jpg',
                            'buildingsorigin/Commercial/INTHEMIX/inthemix2.jpg',
                            'buildingsorigin/Commercial/INTHEMIX/inthemix3.jpg',
                            'buildingsorigin/Commercial/INTHEMIX/inthemix4.jpg',
                            'buildingsorigin/Commercial/INTHEMIX/inthemix5.jpg',
                            'buildingsorigin/Commercial/INTHEMIX/inthemix6.jpg'])

commercial.buildings << Building.create(name: 'ARRIVALS',
                description: '',
                year: '2019',
                location: 'Mexico City',
                area: '150.00 sqm',
                thumbnail: 'thumbnail/inthemix.jpg',
                images: ['https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals1.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals2.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514178/Arrivals/arrivals3.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals4.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals5.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514175/Arrivals/arrivals6.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514176/Arrivals/arrivals7.jpg'],
                imagesori: ['https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals1.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals2.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514178/Arrivals/arrivals3.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals4.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals5.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514175/Arrivals/arrivals6.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514176/Arrivals/arrivals7.jpg'])

commercial.buildings << Building.create(name: 'plaza polanquito',
                description: '',
                year: '2014',
                location: 'Mexico City',
                area: '870.00 sqm',
                thumbnail: 'thumbnail/commercial/polanquitom.jpg',
                images: ['buildings/plaza-polanquito/polanquito1.jpg',
                         'buildings/plaza-polanquito/polanquito2.jpg',
                         'buildings/plaza-polanquito/polanquito3.jpg',
                         'buildings/plaza-polanquito/polanquito4.jpg'],
                imagesori: ['buildingsorigin/Commercial/PLAZAPOLANQUITO/polanquito1.jpg',
                            'buildingsorigin/Commercial/PLAZAPOLANQUITO/polanquito2.jpg',
                            'buildingsorigin/Commercial/PLAZAPOLANQUITO/polanquito3.jpg',
                            'buildingsorigin/Commercial/PLAZAPOLANQUITO/polanquito5.jpg'])

building = Building.create(name: 'Paddock interprotección',
                description: '',
                year: '2019',
                location: 'Mexico City',
                area: '640.00 sqm',
                thumbnail: 'https://res.cloudinary.com/ablanco/image/upload/v1576101933/interproteccion.jpg',
                images: ['https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter1.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter2.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter3.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter4.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter5.jpg'],
                imagesori: ['https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter1.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter2.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter3.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter4.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576102319/interproteccion/inter5.jpg'])

commercial.buildings << building
office.buildings << building


# -----------------------------------------------------------------------------
puts 'office --> 2'
office.buildings << Building.create(name: '​jz offices',
                description: '',
                year: '2015',
                location: 'Mexico City',
                area: '275.00 sqm',
                thumbnail: 'thumbnail/jz.jpg',
                images: ['buildings/​jz-offices/jz1.jpg',
                         'buildings/​jz-offices/jz2.jpg',
                         'buildings/​jz-offices/jz3.jpg',
                         'buildings/​jz-offices/jz4.jpg',
                         'buildings/​jz-offices/jz5.jpg'],
                imagesori: ['buildings/​jz-offices/jz1.jpg',
                            'buildingsorigin/Office/jz-offices/JZOFFICES2.jpg',
                            'buildingsorigin/Office/jz-offices/JZOFFICES3.jpg',
                            'buildingsorigin/Office/jz-offices/JZOFFICES4.jpg',
                            'buildingsorigin/Office/jz-offices/JZOFFICES5.jpg'])


building = Building.create(name: '​max mix',
                description: '',
                year: '2012',
                location: 'Mexico City',
                area: '14,500.00 sqm',
                thumbnail: 'thumbnail/office/maxmixm.jpg',
                images: ['buildings/max-mix/MAXMIX2.jpg',
                         'buildings/max-mix/MAXMIX3.jpg',
                         'buildings/max-mix/MAXMIX4.jpg',
                         'buildings/max-mix/MAXMIX5.jpg',
                         'buildings/max-mix/MAXMIX1.jpg'],
                imagesori: ['buildingsorigin/Office/MAXMIX/MAXMIX2.jpg',
                            'buildingsorigin/Office/MAXMIX/MAXMIX3.jpg',
                            'buildingsorigin/Office/MAXMIX/MAXMIX4.jpg',
                            'buildingsorigin/Office/MAXMIX/MAXMIX5.jpg',
                            'buildingsorigin/Office/MAXMIX/maxmix1.jpg'])

office.buildings << building
commercial.buildings << building



# building = Building.create(name: 'reforma 341',
#                 description: '',
#                 year: '2008',
#                 location: 'Mexico City',
#                 area: '250,000.00 sqm',
#                 thumbnail: 'thumbnail/office/reformam.jpg',
#                 images: ['buildings/reforma-341/REFORMA-341-1.jpg',
#                          'buildings/reforma-341/REFORMA-341-2.jpg',
#                          'buildings/reforma-341/REFORMA-341-3.jpg',
#                          'buildings/reforma-341/REFORMA-341-4.jpg'])

# commercial.buildings << building
# residential.buildings << building
# office.buildings << building




office.buildings << Building.create(name: 'winsor headquarters',
                description: '',
                year: '2017',
                location: 'Mexico City',
                area: '580 sqm',
                thumbnail: 'thumbnail/windsor.jpg',
                images: ['buildings/winsor-headquarters/winsor1.jpg',
                         'buildings/winsor-headquarters/winsor2.jpg',
                         'buildings/winsor-headquarters/winsor3.jpg',
                         'buildings/winsor-headquarters/winsor4.jpg',
                         'buildings/winsor-headquarters/winsor5.jpg',
                         'buildings/winsor-headquarters/winsor6.jpg',
                         'buildings/winsor-headquarters/winsor7.jpg',
                         'buildings/winsor-headquarters/winsor8.jpg',
                         'buildings/winsor-headquarters/winsor9.jpg',
                         'buildings/winsor-headquarters/winsor10.jpg',
                         'buildings/winsor-headquarters/winsor11.jpg',
                         'buildings/winsor-headquarters/winsor12.jpg'],
                imagesori: ['buildingsorigin/Office/WINSOR/windsor1.jpg',
                            'buildingsorigin/Office/WINSOR/windsor2.jpg',
                            'buildingsorigin/Office/WINSOR/windsor3.jpg',
                            'buildingsorigin/Office/WINSOR/windsor4.jpg',
                            'buildingsorigin/Office/WINSOR/windsor5.jpg',
                            'buildingsorigin/Office/WINSOR/windsor6.jpg',
                            'buildingsorigin/Office/WINSOR/windsor7.jpg',
                            'buildingsorigin/Office/WINSOR/windsor8.jpg',
                            'buildingsorigin/Office/WINSOR/windsor9.jpg',
                            'buildingsorigin/Office/WINSOR/windsor10.jpg',
                            'buildingsorigin/Office/WINSOR/windsor11.jpg',
                            'buildingsorigin/Office/WINSOR/windsor12.jpg'])



office.buildings << Building.create(name: 'Abanca Mexico',
                description: '',
                year: '2017',
                location: 'Mexico City',
                area: '300 sqm',
                thumbnail: 'thumbnail/abanca.jpg',
                images: ['buildings/ABANCAMEXICO/abanca1.jpg',
                         'buildings/ABANCAMEXICO/abanca2.jpg',
                         'buildings/ABANCAMEXICO/abanca3.jpg',
                         'buildings/ABANCAMEXICO/abanca4.jpg',
                         'buildings/ABANCAMEXICO/abanca5.jpg',
                         'buildings/ABANCAMEXICO/abanca6.jpg',
                         'buildings/ABANCAMEXICO/abanca7.jpg',
                         'buildings/ABANCAMEXICO/abanca8.jpg'],
                imagesori: ['buildingsorigin/Office/ABANCAMEXICO/abanca1.jpg',
                            'buildingsorigin/Office/ABANCAMEXICO/abanca2.jpg',
                            'buildingsorigin/Office/ABANCAMEXICO/abanca3.jpg',
                            'buildingsorigin/Office/ABANCAMEXICO/abanca4.jpg',
                            'buildingsorigin/Office/ABANCAMEXICO/abanca5.jpg',
                            'buildingsorigin/Office/ABANCAMEXICO/abanca6.jpg',
                            'buildingsorigin/Office/ABANCAMEXICO/abanca7.jpg',
                            'buildingsorigin/Office/ABANCAMEXICO/abanca8.jpg'])


office.buildings << Building.create(name: 'Jacobs México',
                description: '',
                year: '2018',
                location: 'Mexico City',
                area: '450 sqm',
                thumbnail: 'thumbnail/jacobs.jpg',
                images: ['buildings/JACOBSMEXICO/jacobs1.jpg',
                         'buildings/JACOBSMEXICO/jacobs2.jpg',
                         'buildings/JACOBSMEXICO/jacobs3.jpg',
                         'buildings/JACOBSMEXICO/jacobs4.jpg',
                         'buildings/JACOBSMEXICO/jacobs5.jpg',
                         'buildings/JACOBSMEXICO/jacobs6.jpg',
                         'buildings/JACOBSMEXICO/jacobs7.jpg',
                         'buildings/JACOBSMEXICO/jacobs8.jpg',
                         'buildings/JACOBSMEXICO/jacobs9.jpg',
                         'buildings/JACOBSMEXICO/jacobs10.jpg'],
                imagesori: ['buildingsorigin/Office/JACOBSMEXICO/jacobs1.jpg',
                            'buildingsorigin/Office/JACOBSMEXICO/jacobs2.jpg',
                            'buildingsorigin/Office/JACOBSMEXICO/jacobs3.jpg',
                            'buildingsorigin/Office/JACOBSMEXICO/jacobs4.jpg',
                            'buildingsorigin/Office/JACOBSMEXICO/jacobs5.jpg',
                            'buildingsorigin/Office/JACOBSMEXICO/jacobs6.jpg',
                            'buildingsorigin/Office/JACOBSMEXICO/jacobs7.jpg',
                            'buildingsorigin/Office/JACOBSMEXICO/jacobs8.jpg',
                            'buildingsorigin/Office/JACOBSMEXICO/jacobs9.jpg',
                            'buildingsorigin/Office/JACOBSMEXICO/jacobs10.jpg'])



office.buildings << Building.create(name: 'Ethan gas oil',
                description: '',
                year: '2014',
                location: 'Mexico City',
                area: '530 sqm',
                thumbnail: 'thumbnail/ethan.jpg',
                images: ['buildings/ETHAN/ethan1.jpg',
                         'buildings/ETHAN/ethan2.jpg',
                         'buildings/ETHAN/ethan3.jpg',
                         'buildings/ETHAN/ethan4.jpg'],
                imagesori: ['buildingsorigin/Office/ETHAN/ethan1.jpg',
                            'buildingsorigin/Office/ETHAN/ethan2.jpg',
                            'buildingsorigin/Office/ETHAN/ethan3.jpg',
                            'buildingsorigin/Office/ETHAN/ethan4.jpg'])


office.buildings << Building.create(name: 'eg headquarters',
                description: '',
                year: '2014',
                location: 'Mexico City',
                area: '410 sqm',
                thumbnail: 'thumbnail/eg.jpg',
                images: ['buildings/eg-headquarters/EGHEADQUARTERS1.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS2.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS3.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS4.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS5.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS6.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS7.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS8.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS9.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS10.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS11.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS12.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS13.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS14.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS15.jpg',
                         'buildings/eg-headquarters/EGHEADQUARTERS16.jpg'],
                imagesori: ['buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS1.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS2.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS3.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS4.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS5.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS6.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS7.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS8.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS9.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS10.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS11.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS12.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS13.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS14.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS15.jpg',
                            'buildingsorigin/Office/EGHEADQUARTERS/EGHEADQUARTERS16.jpg'])



# -----------------------------------------------------------------------------
puts 'health --> 3'


# -----------------------------------------------------------------------------
puts 'education --> 4'
education.buildings << Building.create(name: 'cuajimalpa community center',
                description: '',
                year: '2011',
                location: 'Mexico City',
                area: '22,000.00 sqm',
                thumbnail: 'thumbnail/education/cuajimalpa.jpg',
                images: ['buildings/cuajimalpa-community-center/cuajimalpa1.jpg',
                         'buildings/cuajimalpa-community-center/cuajimalpa2.jpg',
                         'buildings/cuajimalpa-community-center/cuajimalpa3.jpg',
                         'buildings/cuajimalpa-community-center/cuajimalpa4.jpg',
                         'buildings/cuajimalpa-community-center/cuajimalpa5.jpg',
                         'buildings/cuajimalpa-community-center/cuajimalpa6.jpg'],
                imagesori: ['buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC1.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC2.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC3.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC4.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC5.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC6.jpg'])


education.buildings << Building.create(name: 'Vasconcelos Elementary',
                description: '',
                year: '2011',
                location: 'Mexico City',
                area: '22,100.00 sqm',
                thumbnail: 'thumbnail/vasconcelos.jpg',
                images: ['buildings/VASCONCELOS/vasconcelos1.jpg',
                         'buildings/VASCONCELOS/vasconcelos2.jpg',
                         'buildings/VASCONCELOS/vasconcelos3.jpg',
                         'buildings/VASCONCELOS/vasconcelos4.jpg',
                         'buildings/VASCONCELOS/vasconcelos5.jpg',
                         'buildings/VASCONCELOS/vasconcelos6.jpg',
                         'buildings/VASCONCELOS/vasconcelos7.jpg'],
                imagesori: ['buildingsorigin/Education/VASCONCELOS/vasconcelos1.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos2.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos3.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos4.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos5.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos6.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos7.jpg'])



# -----------------------------------------------------------------------------
puts 'cultural --> 5'
building = Building.create(name: 'chapultepec library',
                description: '',
                year: '2010',
                location: 'Mexico City',
                area: '13,000.00 sqm',
                thumbnail: 'thumbnail/cultural/chapultepecm.jpg',
                images: ['buildings/chapultepec-library/chapultepec1.jpg',
                         'buildings/chapultepec-library/chapultepec2.jpg',
                         'buildings/chapultepec-library/chapultepec3.jpg',
                         'buildings/chapultepec-library/chapultepec4.jpg',
                         'buildings/chapultepec-library/chapultepec5.jpg',
                         'buildings/chapultepec-library/chapultepec6.jpg'],
                imagesori: ['buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY6.jpg',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY2.jpg',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY3.JPG',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY4.jpg',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY5.JPG',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY1.jpg'])

cultural.buildings << building
publics.buildings << building


building = Building.create(name: 'minm museum',
                description: '',
                year: '2009',
                location: 'Mexico City',
                area: '11,000.00 sqm',
                thumbnail: 'thumbnail/minim.jpg',
                images: ['buildings/minm-museum/minim1.jpg',
                         'buildings/minm-museum/minim2.jpg',
                         'buildings/minm-museum/minim3.jpg',
                         'buildings/minm-museum/minim4.jpg'],
                imagesori: ['buildingsorigin/Cultural/MINMMUSEUM/MINMMUSEUM1.jpg',
                            'buildingsorigin/Cultural/MINMMUSEUM/MINMMUSEUM2.jpg',
                            'buildingsorigin/Cultural/MINMMUSEUM/MINMMUSEUM3.jpg',
                            'buildingsorigin/Cultural/MINMMUSEUM/MINMMUSEUM4.jpg'])

cultural.buildings << building
publics.buildings << building



# -----------------------------------------------------------------------------
puts 'publics --> 6'
building = Building.create(name: 'toluca convention center',
                description: '',
                year: '2012',
                location: 'Toluca, Estado de Mexico',
                area: '160,000.00 sqm',
                thumbnail: 'thumbnail/tolucacc.jpg',
                images: ['buildings/toluca-convention-center/toluca1.jpg',
                         'buildings/toluca-convention-center/TOLUCACC2.jpg',
                         'buildings/toluca-convention-center/TOLUCACC3.jpg',
                         'buildings/toluca-convention-center/TOLUCACC4.jpg',
                         'buildings/toluca-convention-center/TOLUCACC5.jpg',
                         'buildings/toluca-convention-center/TOLUCACC6.jpg',
                         'buildings/toluca-convention-center/TOLUCACC7.jpg',
                         'buildings/toluca-convention-center/TOLUCACC8.jpg'],
                imagesori: ['buildingsorigin/Public/TOLUCA/TOLUCACC1.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC2.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC3.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC4.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC5.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC6.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC7.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC8.jpg'])

publics.buildings << building
commercial.buildings << building