
puts 'Residential --> 0'
residential = Kind.create(name: 'residential')
commercial = Kind.create(name: 'commercial')
office = Kind.create(name: 'office')
# health = Kind.create(name: 'health')
education = Kind.create(name: 'education')
cultural = Kind.create(name: 'cultural')
publics = Kind.create(name: 'publics')


residential.buildings << Building.create(name: 'ahuehuetes 2105',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '435.00 sqm' ,
                thumbnail: 'thumbnail/ahuehuetes.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes6.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ahuehuetes-2105/ahuehuetes6.jpg'])


residential.buildings << Building.create(name: 'Sauces 902',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '315.00 sqm' ,
                thumbnail: 'https://aldofranco.s3.amazonaws.com/projects/buildings/sauces/SAUSE.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/sauces/SAUSES1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/sauces/SAUSES2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/sauces/SAUSES3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/sauces/SAUSES4.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/sauces/SAUSES1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/sauces/SAUSES2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/sauces/SAUSES3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/sauces/SAUSES4.jpg'])


residential.buildings << Building.create(name: 'Carso AP',
                description: '',
                year: '2017',
                location: 'Mexico City',
                area: '350.00 sqm' ,
                thumbnail: 'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/carsom.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP12.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP13.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP14.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP15.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP12.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP13.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP14.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/carso/CARSOAP15.jpg'])

residential.buildings << Building.create(name: 'bosque de canelos',
                description: '',
                year: '2015',
                location: 'Mexico City',
                area: '320 sqm' ,
                thumbnail: 'thumbnail/residential/bosquedecanelos.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS12.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/bosque-de-canelos/CANELOS12.jpg'])


residential.buildings << Building.create(name: 'departamento ppg',
                description: '',
                year: '2018',
                location: 'Mexico City',
                area: '430 sqm' ,
                thumbnail: 'thumbnail/ppg.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg5.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/departamento-ppg/departamentoppg5.jpg'])

residential.buildings << Building.create(name: 'San Nicolás VV',
                description: '',
                year: '2019',
                location: 'Valle de Bravo',
                area: '22,000 sqm' ,
                thumbnail: 'https://res.cloudinary.com/ablanco/image/upload/v1576101585/nicolas.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas8.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/SAN_NICOLAS/sannicolas8.jpg'])


residential.buildings << Building.create(name: 'tamarindos 902',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '370.00 sqm' ,
                thumbnail: 'thumbnail/residential/tamarindos.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-5.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/tamarindos-902/TAMARINDOS-902-5.jpg'])



residential.buildings << Building.create(name: 'u house',
                description: '',
                year: '2017',
                location: 'Valle de Bravo',
                area: '610 sqm' ,
                thumbnail: 'thumbnail/uh-house.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse6.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/u-house-bosque-de-canelos/uhouse6.jpg'])

residential.buildings << Building.create(name: 're 32 house',
                description: '',
                year: '2012',
                location: 'Mexico City',
                area: '420 sqm' ,
                thumbnail: 'thumbnail/rehouse.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse7.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/RE32HOUSE/rehouse7.jpg'])

residential.buildings << Building.create(name: 'Avandaro',
                description: '',
                year: '2021',
                location: 'Mexico City',
                area: '310 sqm' ,
                thumbnail: 'thumbnail/residential/avandarothum.png',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/avandaro/avandaro1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/avandaro/avandaro2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/avandaro/avandaro3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/avandaro/avandaro4.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/avandaro/avandaro1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/avandaro/avandaro2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/avandaro/avandaro3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/avandaro/avandaro4.jpg'])

residential.buildings << Building.create(name: 'Paseo de Laureles',
                description: '',
                year: '2021',
                location: 'Mexico City',
                area: '910 sqm' ,
                thumbnail: 'thumbnail/residential/laurelesthum.png',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles3.png',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles4.png',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles5.png'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles3.png',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles4.png',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/laureles/laureles5.png'])

residential.buildings << Building.create(name: 'Alcazar de Toledo',
                description: '',
                year: '2021',
                location: 'Mexico City',
                area: '720 sqm' ,
                thumbnail: 'thumbnail/residential/alcazarthum.png',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar7.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/alcazar/alcazar7.jpg'])

building = residential.buildings << Building.create(name: 'Norte 13',
                description: '',
                year: '2021',
                location: 'Mexico City',
                area: '850 sqm' ,
                thumbnail: 'thumbnail/residential/nortethum.png',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/moctezuma/norte1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/moctezuma/norte2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/moctezuma/norte3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/moctezuma/norte4.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/moctezuma/norte1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/moctezuma/norte2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/moctezuma/norte3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/moctezuma/norte4.jpg'])
commercial.buildings << building




# -----------------------------------------------------------------------------
puts 'Commercial --> 1'
commercial.buildings << Building.create(name: 'be concept store',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '300 sqm' ,
                thumbnail: 'thumbnail/commercial/beconceptm.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/beconceptstore1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/beconceptstore2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/beconceptstore3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/beconceptstore4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/beconceptstore5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/beconceptstore6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/beconceptstore7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/beconceptstore8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/beconceptstore9.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/BECONCEPT1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/BECONCEPT2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/BECONCEPT3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/BECONCEPT4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/BECONCEPT5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/BECONCEPT6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/BECONCEPT7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/BECONCEPT8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/be-concept-store/BECONCEPT9.jpg'])

commercial.buildings << Building.create(name: 'Puma México',
                description: '',
                year: '2022
                ',
                location: 'Mexico City',
                area: '1400 sqm' ,
                thumbnail: 'https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera001.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera001.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera002.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera003.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera005.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera006.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera001.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera002.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera003.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera005.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/PUMA/PUMASTORE.V2.PL.010122_PhysCamera006.jpg'])


commercial.buildings << Building.create(name: 'raw republic',
                description: '',
                year: '2017',
                location: 'Mexico City',
                area: '280 sqm' ,
                thumbnail: 'thumbnail/commercial/rawrepublicm.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC14.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC12.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC13.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC8.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC14.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC12.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC13.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/raw-republic/RAWREPUBLIC8.jpg'])


commercial.buildings << Building.create(name: 'ten tei',
                description: '',
                year: '2018',
                location: 'Mexico City',
                area: '70 sqm',
                thumbnail: 'thumbnail/commercial/tenteim.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI12.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI9.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI12.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ten-tei/TENTEI9.jpg'])

commercial.buildings << Building.create(name: 'in the mix',
                description: '',
                year: '2016',
                location: 'Mexico City',
                area: '110.00 sqm',
                thumbnail: 'thumbnail/inthemix.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX6.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/in-the-mix/INTHEMIX6.jpg'])

commercial.buildings << Building.create(name: 'ARRIVALS',
                description: '',
                year: '2019',
                location: 'Mexico City',
                area: '150.00 sqm',
                thumbnail: 'thumbnail/arrivals.jpg',
                images: ['https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals1.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals2.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514178/Arrivals/arrivals3.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals4.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals5.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514175/Arrivals/arrivals6.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514176/Arrivals/arrivals7.jpg'],
                imagesori: ['https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals1.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals2.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514178/Arrivals/arrivals3.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals4.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514179/Arrivals/arrivals5.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514175/Arrivals/arrivals6.jpg',
                         'https://res.cloudinary.com/ablanco/image/upload/v1576514176/Arrivals/arrivals7.jpg'])

commercial.buildings << Building.create(name: 'plaza polanquito',
                description: '',
                year: '2014',
                location: 'Mexico City',
                area: '870.00 sqm',
                thumbnail: 'thumbnail/commercial/polanquitom.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/plaza-polanquito/polanquito1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/plaza-polanquito/polanquito2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/plaza-polanquito/polanquito3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/plaza-polanquito/polanquito4.jpg'],
                imagesori: ['buildingsorigin/Commercial/PLAZAPOLANQUITO/polanquito1.jpg',
                            'buildingsorigin/Commercial/PLAZAPOLANQUITO/polanquito2.jpg',
                            'buildingsorigin/Commercial/PLAZAPOLANQUITO/polanquito3.jpg',
                            'buildingsorigin/Commercial/PLAZAPOLANQUITO/polanquito5.jpg'])

building = Building.create(name: 'Brokers Paddock',
                description: '',
                year: '2019',
                location: 'Mexico City',
                area: '640.00 sqm',
                thumbnail: 'https://res.cloudinary.com/ablanco/image/upload/v1576101933/interproteccion.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter5.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/INTERPROTECCION/inter5.jpg'])

commercial.buildings << building
office.buildings << building


# -----------------------------------------------------------------------------
puts 'office --> 2'
office.buildings << Building.create(name: '​jz offices',
                description: '',
                year: '2015',
                location: 'Mexico City',
                area: '275.00 sqm',
                thumbnail: 'thumbnail/jz.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz5.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/jz-offices/jz5.jpg'])

building = Building.create(name: 'Elefantec Global',
                description: '',
                year: '2021',
                location: 'Mexico City',
                area: '300 sqm',
                thumbnail: 'thumbnail/office/elefantecthum.png',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/elefantec/elefantec1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/elefantec/elefantec2.png',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/elefantec/elefantec3.png',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/elefantec/elefantec4.png'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/elefantec/elefantec1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/elefantec/elefantec2.png',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/elefantec/elefantec3.png',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/elefantec/elefantec4.png'])
office.buildings << building

building = Building.create(name: 'Metalitec',
                description: '',
                year: '2020',
                location: 'Mexico City',
                area: '1200 sqm',
                thumbnail: 'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V1.PL.160520_Camera010-copia.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V1.PL.160520_Camera010-copia.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera001-copia-(2).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera002-copia-(3).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera002-copia-(3).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera003-copia-(2).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera004-copia-(2).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera011-copia-(2).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera012-copia-(2).jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V1.PL.160520_Camera010-copia.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera001-copia-(2).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera002-copia-(3).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera002-copia-(3).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera003-copia-(2).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera004-copia-(2).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera011-copia-(2).jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/METALITEC/OFICINAS.SANISIDRO.V12.PL.170620_Camera012-copia-(2).jpg'])
office.buildings << building

building = Building.create(name: '​max mix',
                description: '',
                year: '2012',
                location: 'Mexico City',
                area: '14,500.00 sqm',
                thumbnail: 'thumbnail/office/maxmixm.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX5.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/max-mix/MAXMIX5.jpg'])

office.buildings << building
commercial.buildings << building



# building = Building.create(name: 'reforma 341',
#                 description: '',
#                 year: '2008',
#                 location: 'Mexico City',
#                 area: '250,000.00 sqm',
#                 thumbnail: 'thumbnail/office/reformam.jpg',
#                 images: ['buildings/reforma-341/REFORMA-341-1.jpg',
#                          'buildings/reforma-341/REFORMA-341-2.jpg',
#                          'buildings/reforma-341/REFORMA-341-3.jpg',
#                          'buildings/reforma-341/REFORMA-341-4.jpg'])

# commercial.buildings << building
# residential.buildings << building
# office.buildings << building




office.buildings << Building.create(name: 'winsor headquarters',
                description: '',
                year: '2017',
                location: 'Mexico City',
                area: '580 sqm',
                thumbnail: 'thumbnail/windsor.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor12.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/winsor-headquarters/winsor12.jpg'])



office.buildings << Building.create(name: 'Abanca Mexico',
                description: '',
                year: '2017',
                location: 'Mexico City',
                area: '300 sqm',
                thumbnail: 'thumbnail/abanca.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca8.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca3.jpg',
                         'buildings/ABANCAMEXICO/abanca4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ABANCAMEXICO/abanca8.jpg'])


office.buildings << Building.create(name: 'Jacobs México',
                description: '',
                year: '2018',
                location: 'Mexico City',
                area: '450 sqm',
                thumbnail: 'thumbnail/jacobs.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs10.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/JACOBSMEXICO/jacobs10.jpg'])



office.buildings << Building.create(name: 'Ethan gas oil',
                description: '',
                year: '2014',
                location: 'Mexico City',
                area: '530 sqm',
                thumbnail: 'thumbnail/ethan.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/ETHAN/ethan1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ETHAN/ethan2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ETHAN/ethan3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ETHAN/ethan4.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/ETHAN/ethan1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ETHAN/ethan2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ETHAN/ethan3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/ETHAN/ethan4.jpg'])


office.buildings << Building.create(name: 'eg headquarters',
                description: '',
                year: '2014',
                location: 'Mexico City',
                area: '410 sqm',
                thumbnail: 'thumbnail/eg.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS12.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS13.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS14.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS15.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS16.jpg'],
                imagesori: ['https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS8.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS9.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS10.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS11.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS12.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS13.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS14.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS15.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/eg-headquarters/EGHEADQUARTERS16.jpg'])



# -----------------------------------------------------------------------------
puts 'health --> 3'


# -----------------------------------------------------------------------------
puts 'education --> 4'
education.buildings << Building.create(name: 'cuajimalpa community center',
                description: '',
                year: '2011',
                location: 'Mexico City',
                area: '22,000.00 sqm',
                thumbnail: 'thumbnail/education/cuajimalpa.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/cuajimalpa-community-center/cuajimalpa1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/cuajimalpa-community-center/cuajimalpa2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/cuajimalpa-community-center/cuajimalpa3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/cuajimalpa-community-center/cuajimalpa4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/cuajimalpa-community-center/cuajimalpa5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/cuajimalpa-community-center/cuajimalpa6.jpg'],
                imagesori: ['buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC1.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC2.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC3.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC4.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC5.jpg',
                            'buildingsorigin/Education/CUAJIMALPA/CUAJIMALPACC6.jpg'])


education.buildings << Building.create(name: 'Vasconcelos Elementary',
                description: '',
                year: '2011',
                location: 'Mexico City',
                area: '22,100.00 sqm',
                thumbnail: 'thumbnail/vasconcelos.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/VASCONCELOS/vasconcelos1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/VASCONCELOS/vasconcelos2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/VASCONCELOS/vasconcelos3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/VASCONCELOS/vasconcelos4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/VASCONCELOS/vasconcelos5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/VASCONCELOS/vasconcelos6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/VASCONCELOS/vasconcelos7.jpg'],
                imagesori: ['buildingsorigin/Education/VASCONCELOS/vasconcelos1.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos2.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos3.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos4.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos5.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos6.jpg',
                            'buildingsorigin/Education/VASCONCELOS/vasconcelos7.jpg'])



# -----------------------------------------------------------------------------
puts 'cultural --> 5'
building = Building.create(name: 'chapultepec library',
                description: '',
                year: '2010',
                location: 'Mexico City',
                area: '13,000.00 sqm',
                thumbnail: 'thumbnail/cultural/chapultepecm.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/chapultepec-library/chapultepec1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/chapultepec-library/chapultepec2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/chapultepec-library/chapultepec3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/chapultepec-library/chapultepec4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/chapultepec-library/chapultepec5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/chapultepec-library/chapultepec6.jpg'],
                imagesori: ['buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY6.jpg',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY2.jpg',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY3.JPG',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY4.jpg',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY5.JPG',
                            'buildingsorigin/Cultural/CHAPULTEPECLIBRARY/CHAPULTEPEC-LIBRARY1.jpg'])

cultural.buildings << building
publics.buildings << building


building = Building.create(name: 'minm museum',
                description: '',
                year: '2009',
                location: 'Mexico City',
                area: '11,000.00 sqm',
                thumbnail: 'thumbnail/minim.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/minm-museum/minim1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/minm-museum/minim2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/minm-museum/minim3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/minm-museum/minim4.jpg'],
                imagesori: ['buildingsorigin/Cultural/MINMMUSEUM/MINMMUSEUM1.jpg',
                            'buildingsorigin/Cultural/MINMMUSEUM/MINMMUSEUM2.jpg',
                            'buildingsorigin/Cultural/MINMMUSEUM/MINMMUSEUM3.jpg',
                            'buildingsorigin/Cultural/MINMMUSEUM/MINMMUSEUM4.jpg'])

cultural.buildings << building
publics.buildings << building



# -----------------------------------------------------------------------------
puts 'publics --> 6'
building = Building.create(name: 'toluca convention center',
                description: '',
                year: '2012',
                location: 'Toluca, Estado de Mexico',
                area: '160,000.00 sqm',
                thumbnail: 'thumbnail/tolucacc.jpg',
                images: ['https://aldofranco.s3.amazonaws.com/projects/buildings/toluca-convention-center/toluca1.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/toluca-convention-center/TOLUCACC2.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/toluca-convention-center/TOLUCACC3.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/toluca-convention-center/TOLUCACC4.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/toluca-convention-center/TOLUCACC5.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/toluca-convention-center/TOLUCACC6.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/toluca-convention-center/TOLUCACC7.jpg',
                         'https://aldofranco.s3.amazonaws.com/projects/buildings/toluca-convention-center/TOLUCACC8.jpg'],
                imagesori: ['buildingsorigin/Public/TOLUCA/TOLUCACC1.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC2.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC3.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC4.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC5.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC6.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC7.jpg',
                            'buildingsorigin/Public/TOLUCA/TOLUCACC8.jpg'])

publics.buildings << building
commercial.buildings << building